### ISSUE TITLE
Can I do this in rpi 4 with 1gb or Not? Or only in rpi4 with 4gb and/or 8gb

### ISSUE THREAD

**Issue by neuberfran** [TImada/raspi4_freertos_rpmsg#1]
Hi,

Can I do this in rpi 4 with 1gb or Not? Or only in rpi4 with 4gb and/or 8gb.

I'm trying to put ubuntu 22.04.1 on rpi4 1gb and I'm not getting it.

I've been playing with iot for 8 years now.

I've done RPMsg (no remoteproc, bootloader only) on imx7d_pico using Yocto(hardknott) and FreeRtos.

My project dream is to Blink a led using Push utton Switch on the a7 part and the led on the m4 part,
Or, in the case of rpi4 1gb, use pushbutton switch in Core 0/Linux and Led in Core 3/FreeRtos
![image](https://user-images.githubusercontent.com/38701397/196469813-0d91c020-c64b-44b0-8cd4-ab4e6cf2a93e.png)

**Comment by TImada** [comment]
> Can I do this in rpi 4 with 1gb or Not? Or only in rpi4 with 4gb and/or 8gb.

Yes, this RPMSG sample should work on 1GB RAM version of Raspi4B.

> My project dream is to Blink a led using Push utton Switch on the a7 part and the led on the m4 part, Or, in the case of rpi4 1gb, use pushbutton switch in Core 0/Linux and Led in Core 3/FreeRtos

This porting does not include any device driver other than that for PL011 UARTs. Therefore, you will need to implement  a GPIO driver to manipulate buttons and LEDs on Raspi4B.
Using i.MX7D seems better in reducing implementation cost as NXP provides a variety of device drivers on their processors. :-)

**Comment by neuberfran** [comment]
@TImada I prefer Rpi4 because I prefer remoteproc of the your project. I stay trying RPMsg in Linux/RTOS after boot. I prefer use remoteproc

**Comment by neuberfran** [comment]
@TImada 

This is my config.txt in rpi4 1gb
```

kernel=u-boot.bin
arm_64bit=1
init_uart_clock=3000000
enable_uart=1
core_freq=250
disable_overscan=1
```

My issue now is:

bcmgenet: PHY startup failed+Retrieving file: pxelinux.cfg/00000000 ethernet@7d580000 Waiting for PHY auto negotiation to complete


I couldn't install ubuntu core or debian on this rpi4 1gb. Just installed the latest official raspbian version

please help me

**Comment by TImada** [comment]
> bcmgenet: PHY startup failed+Retrieving file: pxelinux.cfg/00000000 ethernet@7d580000 Waiting for PHY auto negotiation to complete

This seems a log during IP address requesting from a DHCP client for PXEBOOT. Wrong OS image for netboot ?
(This error should be discussed at https://www.raspbian.org/RaspbianForums as it is not related to FreeRTOS porting at all.)

**Comment by neuberfran** [comment]
@TImada 
https://hechao.li/2021/12/20/Boot-Raspberry-Pi-4-Using-uboot-and-Initramfs/

This is my option to put u-boot/Linux in my Rpi4

But I have problem in the mentioned tutorial:

```
My linux in crosstol-ng is 6.0.2. But in your tutorial in 5.1 part (5.1 Download the Kernel Source) "Also note that the kernel version must be higher than the kernel version configured for the toolchain."

I can't find linux higher than 5.15 in this site:

https://github.com/raspberrypi/linux

How can I solve it?

Pls
```

If you can help resolve this issue of this tutorial, I would appreciate it.

**Comment by neuberfran** [comment]
@TImada 

There is another strange error here in **u-boot** which is as follows:

I get to the part: **Hit any key to stop autoboot: 2**  where I try to stop u-boot to type the envimoments and arguments (as pictured below), but it doesn't stop, I don't know why.

![photo01](https://user-images.githubusercontent.com/38701397/197246847-52e0d7a9-fd11-47d4-b32e-7d3d267a2c53.png)
![photo02](https://user-images.githubusercontent.com/38701397/197246871-324cea7c-368e-42f5-bd93-d4fa25d3f0eb.png)

**Comment by TImada** [comment]
> @TImada https://hechao.li/2021/12/20/Boot-Raspberry-Pi-4-Using-uboot-and-Initramfs/
> 
> This is my option to put u-boot/Linux in my Rpi4
> ...
> ...
> If you can help resolve this issue of this tutorial, I would appreciate it.

I've never tried a Busybox-based OS image for my FreeRTOS porting to Raspi4B. Any useful comment from me cannot be expected unfortunately.
(This repository assumes that you use a Ubuntu-based (or Debian-based) OS image)

> I get to the part: Hit any key to stop autoboot: 2 where I try to stop u-boot to type the environments and arguments (as pictured below), but it doesn't stop, I don't know why.

Check the followings below:
- your UART cabling between your Raspi4B board and your PC
- UART connection configuration on your PC (baud rate, data bits, ..., and etc.)

**Comment by neuberfran** [comment]
@TImada my device is raspberry pi 4 1gb(Being 1gb means I have little memory for ubuntu 20.04 core and/or debian)
I bought ftdi with ci cp2102, and Now I have at least i have u-boot
![Captura de tela de 2022-10-25 16-13-26](https://user-images.githubusercontent.com/38701397/197862379-a2b49f97-cd57-4612-8382-f713f4c43602.png)
![Captura de tela de 2022-10-25 16-19-00](https://user-images.githubusercontent.com/38701397/197862718-8c1e80a8-1234-4a06-801d-07fa39477db8.png)

**Comment by TImada** [comment]
You will need to cross-compile a linux side RPMSG sample on your PC if you still use the Busybox-based OS image which does not have build tools such as gcc, make or cmake.
(The Linux sample is assumed to be built on your Raspi4 as I mentioned in [1])

[1] https://github.com/TImada/raspi4_freertos_rpmsg/blob/master/docs/linux_build.md

**Comment by neuberfran** [comment]
@TImada Could you answer two specific questions:

1) Can I run ubuntu and/or debian on rpi4 1gb and that the system is functional?

2) If (and I've already seen that it will be) the answer above is No, what are the steps to follow to get around the problem?

**Comment by TImada** [comment]
> 1. Can I run ubuntu and/or debian on rpi4 1gb and that the system is functional?

This depends on what you want to do on your Raspi4B. For my use case not requiring GUI at all, 1GB RAM is quite enough.

> 2. If (and I've already seen that it will be) the answer above is No, what are the steps to follow to get around the problem?

Use `gcc-aarch64-linux-gnu` and related tools as described in [1]. Compiling the RPMSG sample with the `-static` option is recommended to avoid unexpected errors due to missing dynamic libraries.

[1] https://jensd.be/1126/linux/cross-compiling-for-arm-or-aarch64-on-debian-or-ubuntu

**Comment by neuberfran** [comment]
@TImada 

I managed to climb Rpi4 with u-boot 2021, using buildroot for rpi4_64 and two more commands in the u-boot cli.

I'm going to RPMsg now and I have a question on this line below (see photo, I already got an error in the test for /mnt folder)

**sudo ./u-boot.bin /path/to/sd_boot_partition/kernel8.img**

What is the function of this command above in the RPMsg project of rpi4_64? What is the correct way to run it?

![Screenshot from 2022-10-29 23-37-02](https://user-images.githubusercontent.com/38701397/198860169-c333baea-2c73-4761-935e-8c240544d452.png)

**Comment by TImada** [comment]
That should be `sudo cp ./u-boot.bin /path/to/sd_boot_partition/kernel8.img`.
Thanks!

**Comment by neuberfran** [comment]
@TImada Why I need transform u-boot.bin in kernel8.img

**Comment by TImada** [comment]
Read https://www.raspberrypi.com/documentation/computers/config_txt.html#arm_64bit

**Comment by neuberfran** [comment]
@TImada Up until this point in the tutorial I haven't seen anything on the screen.

Notes: 1) I'm using fatload, because ext4load it didn't work. 1.1) **ls mmc 0:2/tmp** didn't work either.

2) I only have ttyUSB0 open. It's wrong? Should I have already opened ttyUSB1? As?


![Captura de tela de 2022-10-31 18-38-45](https://user-images.githubusercontent.com/38701397/199116672-7290e725-e632-46c5-9ed5-dba44aed679d.png)

**Comment by neuberfran** [comment]
@TImada issue in cmake .. command:

![Captura de tela de 2022-10-31 19-15-11](https://user-images.githubusercontent.com/38701397/199120532-25187452-a378-4cfe-822a-ec0d3d5ab338.png)

**Comment by TImada** [comment]
> 2. I only have ttyUSB0 open. It's wrong? Should I have already opened ttyUSB1? As?

You are wrong. The UART sample uses two different UARTs. (as described in https://github.com/TImada/raspi4_freertos#uart-configuration )

> issue in cmake .. command:

Why don't you check the error log?
It indicates a failure in repository cloning. Did you add `--recursive` at the `git clone` invocation?

**Comment by neuberfran** [comment]
@TImada 

Before answering the above question, I should tell you that I'm having problems with the new device tree that the raspi4_rpmsg project requires:

There are several things to say and demand your attention (please):

https://stackoverflow.com/questions/59580877/raspberry-pi-4-u-boot-on-booting-hanging-in-starting-kernel

On this site above you have the answer of Mr. **marc_s**:

setenv bootargs 8250.nr_uarts=1 console=ttyS0,115200 root=/dev/mmcblk0p2 rootwait rw

fatload mmc 0:1 ${kernel_addr_r} Image
booti ${kernel_addr_r} - ${fdt_addr}

Why didn't I put the dtb on the site above?
**Because if I put linux on it doesn't go up**

In the file below are the 2 dts. Yours and mine. I need your help to make a merge

https://github.com/neuberfran/dts

When I generated the file using dtc it gave the screen error issue99 below

My intention is to put the merged dts file in the dts folder of the buildroot and it will generate a new dtb. Then I can follow the steps of stackoverflow, normally

Note: As per screenshot issue100, I was able to evolve in the command ls mmc 0:2 tmp and I can use ext4load

![issue100](https://user-images.githubusercontent.com/38701397/199312007-4be97bb7-24a8-4f5f-acdb-d9fdf117218c.png)
![issue99](https://user-images.githubusercontent.com/38701397/199312016-212d8b1a-77f9-47df-9037-673710c5c15a.png)

**Comment by neuberfran** [comment]
@TImada 

https://stackoverflow.com/questions/69899667/raspberry-pi-4b-u-boot-bootloader-device-tree-addresses-dtb

![Captura de tela de 2022-11-02 00-01-56](https://user-images.githubusercontent.com/38701397/199385417-48b0edcd-1d87-4151-ab5c-e74a9479e241.png)

**Comment by TImada** [comment]
Unfortunately, I do not have knowledge on how to modify the original *.dts files for this aim.
I modified a dts file disassembled from the bcm2711-rpi-4-b.dtb binary file (= this is a final output dtb).

What I have done on the dts file is as follows:

(Remove `serial1` and `uart0` aliases from the aliases block)
```
    aliases {
        ...
        // serial1 = "/soc/serial@7e201000";
        ...
        // uart0 = "/soc/serial@7e201000";
        ...
     }

```

(Add the `rtos@20000000` block to the `reserved-memory` block)
```
    reserved-memory {
        ...
        ...
        rtos@20000000 {
            compatible = "shared-dma-pool";
            size = <0xA00000>;
            no-map;
            alloc-ranges = <0x0 0x0 0x20000000>;
        };
    };
```

(Add the `shm@20600000`, `armlocal_uio@ff800000` and `gic_uio@40041000` blocks at the same level as the `reserved-memory` block is located)
```
    reserved-memory {
        ...
        ...
    };

    shm@20600000 {
        compatible = "generic-uio";
        status = "okay";
        reg = <0x0 0x20600000 0x200000>;
    };

    armlocal_uio@ff800000 {
        compatible = "generic-uio";
        status = "okay";
        reg = <0x0 0xff800000 0x1000>;
        interrupt-parent = <0x1>;
        interrupts = <0x0 0x0 0x4>;
    };

    gic_uio@40041000 {
        compatible = "generic-uio";
        status = "okay";
        reg = <0x0 0x40041000 0x7000>;
    };
```

**Comment by neuberfran** [comment]
@TImada 

https://forums.raspberrypi.com/viewtopic.php?t=315662
https://www.youtube.com/watch?v=Rp8K0lML4k8

Really, there was a crash here in the tutorial on the issue of device tree deployment (dtb file) on rpi4 through u-boot

As per the links above (my rpi4 is revision 1.2 or higher) there was a change in the dtb file call in u-boot.

Your tutorial is suitable for rpi4 revision 1.1

**Comment by TImada** [comment]
In my understanding, you will need to modify the original *.dts files based on what I have mentioned above, then to build a boot partition in an official manner.

If the error occurs due to the EMMC2 specification change [1] and you can get the `dtc` command on your Raspi4B Linux, the following workaround may work.
(however, I guess that you will have another problem on how to install the `dtc` command in a busybox environment ...)  

1. Create a final dts file by executing `dtc -I fs -O dts -q /proc/device-tree -o bcm2711-rpi-4-b-rtos.dts` on your Raspi4B Linux.
2. Change the final dts file with the modification which I have mentioned above.
3. Compile the changed dts file and obtain `bcm2711-rpi-4-b-rtos.dtb`.
4. Copy `bcm2711-rpi-4-b-rtos.dtb` to the SD card for Raspi4B (and modifiy config.txt so that your Raspi4B can boot with  `bcm2711-rpi-4-b-rtos.dtb`).

[1] https://forums.raspberrypi.com/viewtopic.php?t=315662#p1888661

**Comment by neuberfran** [comment]
@TImada 

Steps 1 and 4 are the ones that make it unfeasible (I've already tried that here). Since there are some #includes in bcm2711-rpi-4-b.dts from buildroot to rpi4. It's not messing with config.txt or the 2 commands I already do in u-boot that will solve (I think)

Friend,

I've been working on this project for two weeks. I tried seadog-gaia (from my friend, link below) and tried yocto on rpi4, but that stopped early on as Noobs for rpi4 didn't work.
https://www.youtube.com/watch?v=GUqcxiw_BsE
https://lancesimms.com/RaspberryPi/HackingRaspberryPi4WithYocto_Introduction.html

What I suggest, for you to help me in the device tree part is the following:

Pull the buildroot, as shown in the video below and apply the following commands (super easy):

https://www.youtube.com/watch?v=9vsu67uMcko&t=827s

1) git clone git://git.buildroot.net/buildroot
2) cd buildroot
3) make raspberrypi4_defconfig
4) make all
4.1) put u-boot.in in boot sdcard partition and change config.txt to kernel=u-boot.bin
https://stackoverflow.com/questions/59580877/raspberry-pi-4-u-boot-on-booting-hanging-in-starting-kernel
4.2) in u-boot cli:
5) setenv bootargs 8250.nr_uarts=1 console=ttyS0,115200 root=/dev/mmcblk0p2 rootwait rw
6) fatload mmc 0:1 ${kernel_addr_r} Image
7) booti ${kernel_addr_r} - ${fdt_addr}



I'm having trouble changing bcm2711-rpi-4-b.dts inside the buildroot folder. Not only because there are several (sudo find. -name bcm2711-rpi-4-b.dts), but after making the changes, How to compile ?

**Comment by TImada** [comment]
> Steps 1 and 4 are the ones that make it unfeasible (I've already tried that here). Since there are some #includes in bcm2711-rpi-4-b.dts from buildroot to rpi4. It's not messing with config.txt or the 2 commands I already do in u-boot that will solve (I think)

Let me check what you have done in the step 1 and 4, before moving to building a modified boot partition.

- How did you get a dts file for compiling by the `dtc` command in the step 1? Is it a dts file which I provided on github?
- How did you load the modified dtb file on your Raspi4B? by the `fatload` or `ext4load` command on the u-boot prompt?

**Comment by neuberfran** [comment]
@TImada 

I use the cp2102 here connected to 5v, otherwise (with the other serial converter) I typed and nothing comes out in uboot.

Today I was without internet and when I came back I had weird characters problems on the screen. It wasn't productive today.

Although I can put noobs on rpi4 and I'll follow the yocto tutorial, mentioned above.

I don't know if the problem is in the converter or in the rpi4 (I hope not)

**Config.txt**

```
[pi4]
kernel=u-boot.bin
max_framebuffers=2

[all]
arm_64bit=1
enable_uart=1
dtparam=i2c=on
dtparam=spi=on
dtparam=act_led_trigger=heartbeat
```
dtparam=pwr_led_trigger=mmc0
dtparam=audio=on
device_tree_address=0x02000000
dtoverlay=disable-bt
dtoverlay=vc4-fkms-v3d,cma-128

**cmdline.txt**
`
root=/dev/mmcblk0p2 rootwait console=tty1 console=ttyAMA0,115200`
![Screenshot from 2022-11-05 01-15-31](https://user-images.githubusercontent.com/38701397/200100521-b0212615-96ba-4059-b0c0-b2f52a2d55a4.png)


![20221105_011601](https://user-images.githubusercontent.com/38701397/200100483-b23b2271-5ad1-4180-9448-9fcb6bbdb363.jpg)

**Comment by TImada** [comment]
`config.txt` seems correct for UART setting, so I cannot say something about what's wrong on your environment.

**Comment by neuberfran** [comment]
@TImada 

Unfortunately my rpi4 died:

https://forums.raspberrypi.com/viewtopic.php?t=342649

While the other is not enough, I want to see how to access the Uart of the gpio14/15 without having to connect the 5v of the cp2102

https://www.youtube.com/watch?v=68DNY0_yxwU&t=312s

**Comment by TImada** [comment]
Which CP2102 board did you use?

**Comment by neuberfran** [comment]
@TImada 

https://produto.mercadolivre.com.br/MLB-2042123322-conversor-usb-serial-uart-cp2102-micro-usb-_JM

**Comment by TImada** [comment]
I cannot find an exact circuit diagram of that board on the web page ...
Anyway ... if the 5V means "output", you do not need to connect it to your Raspi4 board.

In addition, some guys reported that similar boards cannot provide 3.3V on UART [1]. You should check each line on your CP2102 board.

[1] https://forum.arduino.cc/t/usb-to-uart-ttl-ftdi-adapter/611530

**Comment by neuberfran** [comment]
@TImada 

My new rpi4 1gb still hasn't arrived. I'm looking forward to it. In addition to the video below, it explains that changes must be made to config.txt, cmdline.txt(console=ttyS0, in 7'',25''' video) and perhaps to the device tree to have uart using this cp2102, which is the same as the guy in the video uses(without 5v ou 3.3v connection). And, also in the video, it is explained how to recompile the device tree using dtbs. Maybe I can do this in the buildroot, but most likely I'm using a 64bit RaspiOS image and doing something like make ARM=arm64 CROSS_COMPILE=aarch64-linux-gnu-menuconfig using a dts overlay coming from your dts

https://forums.raspberrypi.com/viewtopic.php?t=206750&start=50

https://www.youtube.com/watch?v=68DNY0_yxwU

**Comment by neuberfran** [comment]
> I cannot find an exact circuit diagram of that board on the web page ... Anyway ... if the 5V means "output", you do not need to connect it to your Raspi4 board.
> 
> In addition, some guys reported that similar boards cannot provide 3.3V on UART [1]. You should check each line on your CP2102 board.
> 
> [1] https://forum.arduino.cc/t/usb-to-uart-ttl-ftdi-adapter/611530

Thank you for the informations. I'm reading about it. More information about my cp2102 follows. This photo is what I'm using in this project:

https://www.filipeflop.com/produto/modulo-conversor-usb-ttl-cp2102-serial-rs232/

![20221110_140538](https://user-images.githubusercontent.com/38701397/201168041-b71b0bba-e5d1-4b49-832e-1a0e1bf555d4.jpg)

**Comment by TImada** [comment]
> And, also in the video, it is explained how to recompile the device tree using dtbs. Maybe I can do this in the buildroot, but most likely I'm using a 64bit RaspiOS image and doing something like make ARM=arm64 CROSS_COMPILE=aarch64-linux-gnu-menuconfig using a dts overlay coming from your dts

I have checked the boot sequence of Raspi4B again. What I expect as a dtb file loading method is adding `device_tree=bcm2711-rpi-4-b-rtos.dtb` to `config.txt` (this enables the bootloader to load the modified dtb file) rather than using `fatload ... bcm2711-rpi-4-b-rtos.dtb` (this means device tree data overwriting).

Building a boot partition with a modified dtb file should be of course another way to load the modified dtb file by the bootloader.

**Comment by neuberfran** [comment]
@TImada 

Regarding the two options above, I have 2 questions:

1) Instead of setting the dtb in config.txt (and losing all the other old settings) you came to study about Overlay (where the old settings could be kept and only modify what is different)

2) Would you have the step by step to mount this boot partition? (Quoted in the second part of your answer above)

**Comment by TImada** [comment]
> Instead of setting the dtb in config.txt (and losing all the other old settings) you came to study about Overlay (where the old settings could be kept and only modify what is different)

What is you question on this? Anyway, I do not use any device overlay scheme because it requires further knowledge on device tree management. I prefer to use a disassembled dts file obtained from the original `bcm2711-rpi-4-b.dtb` file.

Loading a modified dtb file with `config.txt` does not mean that the original (old) configuration is lost. Just removing `device_tree=bcm2711-rpi-4-b-rtos.dtb` from `config.txt` is enough for returning your Raspi4B back to the original state. (The original `bcm2711-rpi-4-b.dtb` will be loaded by the bootloader in this case.)

> Would you have the step by step to mount this boot partition? (Quoted in the second part of your answer above)

No, copying `bcm2711-rpi-4-b-rtos.dtb` to the boot partition and modifying `config.txt` are enough.

**Comment by neuberfran** [comment]
> 

Hi,

My friend,

I went back to the project and now I know how to use only 3 wires in the cp2102 (tx, rx and gnd) and it has been working fine.

Excuse me for insisting on this, but I stopped now at the part: "You will see output by the UART sample program."

You can see in the pictures below, my outputs for dmesg | grep "tty"
& ls /dev/tty* & uname -a & arch

You will see in one of the pictures below, that I tried to receive the response screen for the commands:

```
setenv autostart yes
dcache off
fatload mmc 0:1 0x28000000 uart.elf
dcache flush
bootelf 0x28000000
```

on picocom and minicom using 115200 on /dev/ttyUSB0. Is this right? How would it be correct?
![Screenshot from 2022-12-11 21-48-52](https://user-images.githubusercontent.com/38701397/206940719-90fd743e-8297-41c1-bdaa-acbff5d2222d.png)
![Screenshot from 2022-12-11 21-54-17](https://user-images.githubusercontent.com/38701397/206940725-e1a7c9de-88c0-4266-8032-a96f64a7d1f5.png)

**Comment by TImada** [comment]
Your minicom seems to output UART1 data (= UART1 with ALT5 configuration, u-boot prompt).

The UART sample uses UART2 with ALT4 configuration as described in [1]. Make sure that your cp2102 is connected to GPIO0(TXD2), GPIO1(RXD2) and GND.
See "5.3. Alternative Function Assignments" in [2] for the GPIO ALT functionality on BCM2711.

[1] https://github.com/TImada/raspi4_freertos#uart-configuration
[2] https://datasheets.raspberrypi.com/bcm2711/bcm2711-peripherals.pdf

**Comment by neuberfran** [comment]
@TImada 
Will I have to have two cp2102 stuck (3 wires each, totaling 6 wires) in my rpi4 when I give the commands below?

```
setenv autostart yes
dcache off
fatload mmc 0:1 0x28000000 uart.elf
dcache flush
bootelf 0x28000000

```
https://elinux.org/RPi_BCM2711_GPIOs
![Screenshot from 2022-12-14 17-53-03](https://user-images.githubusercontent.com/38701397/207711582-fb935b07-691d-42ea-9947-4ca4a7e347b1.png)

**Comment by TImada** [comment]
> Will I have to have two cp2102 stuck (3 wires each, totaling 6 wires) in my rpi4 when I give the commands below?

Yes.

**Comment by neuberfran** [comment]
@TImada I have result using u-boot commands. But Now I have issue in **make CROSS=aarch64-none-elf-** command (**5. Compile FreeRTOS RPMSG sample**)

```
make CROSS=aarch64-none-elf-
aarch64-none-elf-as -mcpu=cortex-a72 -c -o build/startup.o src/startup.S
Assembler messages:
Fatal error: can't create build/startup.o: No such file or directory
make: *** [Makefile:96: build/startup.o] Error 1
```


![issue](https://user-images.githubusercontent.com/38701397/208557214-978fe3b0-41ea-45fe-836a-0ff2699c24cf.png)
![libmetal](https://user-images.githubusercontent.com/38701397/208557226-9e940fdd-1cac-47d5-8fca-15fb326cc6f7.png)
![open-amp](https://user-images.githubusercontent.com/38701397/208557242-7b70aff0-3917-42e0-8bf4-2f2a7a45117c.png)
![RPMsg_FreeRTOS_RPi4](https://user-images.githubusercontent.com/38701397/208557264-1124612f-ba2d-40bd-be04-74062d574994.png)

**Comment by TImada** [comment]
I've fixed it. Try this repository again with the latest commit @ https://github.com/TImada/raspi4_freertos_rpmsg/commit/4af9d33f1cd38e06e7cfa5dc008e01db6e8fa4aa

**Comment by neuberfran** [comment]
@TImada 

I can create rpmsg_ping.elf in freertos part of the RPMsg project

I have issue in Linux part:
https://github.com/TImada/raspi4_freertos_rpmsg/blob/master/docs/linux_build.md
in 3. **Compile Linux RPMSG sample** (**make** command)

```
make
aarch64-linux-gnu-gcc -mcpu=cortex-a72 -std=gnu99 -O2 -Wall -Wextra -I/usr/local/include -I../../../../open-amp/apps/machine/raspi4 -I../../../common -g3 -c -o objs/main.o ../src/main.c
Assembler messages:
Fatal error: can't create objs/main.o: No such file or directory
make: *** [Makefile:25: objs/main.o] Error 1
```
**Note:**
1) If you look at my penultimate picture below, I have the two files referring to libmetal and open-amp where they should be

2) In my last photo, it shows some corrections that I imagine need to be done in your tutorial. Where it says libmetal, it should say open-amp. I at least put open-amp

3) Another necessary correction is that if you command **export RASPI4_BASE=${PWD}** and then call **cd ${RASPI4_BASE}/libmetal** you will not go to the libmetal folder because the correct thing would be: **cd ${RASPI4_BASE}/raspi4_freertos_rpmsg/libmetal** 

![issue in Linux part of the RPMsg project in Rpi4](https://user-images.githubusercontent.com/38701397/208911029-ea3acdce-0e37-45ba-b3d0-055c1c708f34.png)
![dot H files missing](https://user-images.githubusercontent.com/38701397/208911159-c1a7a947-c0d9-4703-b5b3-3ff617046d8b.png)
![last pic](https://user-images.githubusercontent.com/38701397/208911196-232e59d7-c10a-4b7f-ad27-589938879aef.png)
![last pic_2](https://user-images.githubusercontent.com/38701397/208911234-99e9462e-cc5f-4121-95b8-280b517c4506.png)

**Comment by TImada** [comment]
Try the latest commit @ https://github.com/TImada/raspi4_freertos_rpmsg/commit/4bbf5dd52da68ead4269f1e15e5148d9ef00211c

For Linux side application building, you should have a newly cloned repository of `raspi4_freertos_rpmsg` which is not used to build the FreeRTOS side application (`rpmsg_ping`).

**Comment by neuberfran** [comment]
@TImada issue:

```
sudo ./rpmsg_echo
./rpmsg_echo: error while loading shared libraries: libmetal.so.0: cannot open shared object file: No such file or directory
```
![issue_in_Final_First_PIC](https://user-images.githubusercontent.com/38701397/209409087-c6bd5754-447d-42f0-a2a0-23233724f7c0.png)

![issue_in_Final](https://user-images.githubusercontent.com/38701397/209406720-73ff9929-bfdc-4708-a089-f36e494a044b.png)
![issue_in_Finalb](https://user-images.githubusercontent.com/38701397/209406728-a3118729-b1e4-4de8-b996-c0d20253bc1a.png)

**Comment by TImada** [comment]
Make sure that you have installed both the libmetal and open-amp library files on your Raspi4.

Add the installation path to LD_LIBRARY_PATH if needed.

**Comment by neuberfran** [comment]
@TImada 
1) In this link:
https://github.com/TImada/raspi4_freertos_rpmsg

Part: **3. How to run**
there is nothing to talk about: LD_LIBRARY_PATH 

2) According to the photos above, it can be confirmed with certainty that I have the files generated after compiling libmetal and open-amp. These files are in the folder: **/usr/local/lib**

![last pic](https://user-images.githubusercontent.com/38701397/209565568-52948842-a31a-4851-aaf3-3812a581c1e9.png)

**Comment by TImada** [comment]
> there is nothing to talk about: LD_LIBRARY_PATH

I forgot to describe it because it is usual stuff for my Linux environment! I'll add it later, thanks.

Are you still having the same error? If so, you will have look into your Linux environment.
(I cannot reproduce the error on my Raspi4, and I do not remember any other factor I considered in invocation of the sample program)

**Comment by neuberfran** [comment]
@TImada Yes, I still having the same error:
(You can see in the picture below, that I commanded: export LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib)

**sudo ./rpmsg_echo**
./rpmsg_echo: error while loading shared libraries: libmetal.so.0: cannot open shared object file: No such file or directory
neuberfran@raspberrypi:~/raspi4/raspi4_freertos_rpmsg/samples/linux/rpmsg_echo/build$ **echo $PATH**
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/home/neuberfran/gcc-arm-10.3-2021.07-aarch64-aarch64-none-elf/bin
![Screenshot from 2022-12-28 18-57-05](https://user-images.githubusercontent.com/38701397/209876390-7cfa9da7-e6a6-466b-ac28-737d3d36b8a3.png)

**Comment by neuberfran** [comment]
@TImada 

Really, as pictured below, this last issue is complicated. I have made several attempts and still the same error. I changed the folder to /home/neuberfran/raspi4/raspi4_freertos_rpmsg/libmetal/build/lib/ in order to evade permissions from /usr/local/lib (where I've also done permission change commands) but it still didn't solve it. I tried the commands below and it still didn't work:

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/neuberfran/raspi4/raspi4_freertos_rpmsg/libmetal/build/lib/

![Screenshot from 2022-12-28 22-03-40](https://user-images.githubusercontent.com/38701397/209890677-2bbb83c3-e0cd-406b-9956-39dc184e02bb.png)


I'm trying the steps suggested on stackoverflow below, but when I get to the final command, I get the following error:

https://stackoverflow.com/questions/13428910/how-to-set-the-environmental-variable-ld-library-path-in-linux

**sudo ldconfig
ldconfig: $LD_LIBRARY_PATH:/usr/local/lib is not a known library type**

![Screenshot from 2022-12-28 22-48-23](https://user-images.githubusercontent.com/38701397/209893140-ba00c3c1-c338-44c1-b91e-0a551f531833.png)

**After I reboot I have changes. Tomorrow I will try again. I will be back When I will start FreeRTOS/U-boot part**

![Screenshot from 2022-12-28 23-01-03](https://user-images.githubusercontent.com/38701397/209893767-3b011244-1199-4438-bb32-7527f303c470.png)

**Comment by TImada** [comment]
Errors in the last screenshot indicate that your modification of the device tree was wrong (or you have used the original device tree with out any modification).

**Comment by neuberfran** [comment]
@TImada 
Unfortunately (I thought it would work today) you were right and even going up the FreeRTOS part, it still doesn't work:

The error must be in the device tree, correct?

I thought it would work because I created a *.dtbo (based on your dts) and the site below:
https://bootlin.com/blog/using-device-tree-overlays-example-on-beaglebone-boards/

By the logic of the site above, it should keep everything but the objects that ask to be changed in bcm2711-rpi-4-b-rtos.dtbo

Below, the commands to generate the *.dtbo:

```
dtc -@ -I dts -O dtb -o  bcm2711-rpi-4-b-rtos.dtbo  bcm2711-rpi-4-b-rtos.dts
sudo cp bcm2711-rpi-4-b-rtos.dtbo /boot/overlays/sdcard_partition
```
![Screenshot from 2022-12-29 18-48-21](https://user-images.githubusercontent.com/38701397/210014456-244d92a1-80d5-4f7f-9495-9e0973ed0037.png)
https://www.youtube.com/watch?v=fzcuBZxDnfc

**Comment by TImada** [comment]
You should check the currently loaded device tree by accessing `/proc/device-tree` on a shell of Linux.

In addition, you will have to check i) if or not your overlay file follows the overlay format [1] and ii) if or not your dtbo file loading scheme is correct [2].

[1] https://www.raspberrypi.com/documentation/computers/configuration.html#device-tree-overlays
[2] https://www.raspberrypi.com/documentation/computers/configuration.html#part3

**Comment by neuberfran** [comment]
@TImada 

reulst of the:
find /proc/device-tree/ -type f -exec head {} + | less

https://gist.github.com/neuberfran/7300e10662cd166b40add47df0e11d51

**Comment by TImada** [comment]
Your device tree should have the followings:

`/proc/device-tree/armlocal_uio@ff800000`
`/proc/device-tree/gic_uio@40041000`
`/proc/device-tree/shm@20600000`
`/proc/device-tree/reserved-memory/rtos@20000000`

**Comment by neuberfran** [comment]
@TImada Ok. But how did you get those four lines above?
Do you have rpi4 running now?
I know we already talked about it, but how did you adapt the device tree in rpi4? (I say that from version 1.4 of rpi4 this must have changed)

**Comment by neuberfran** [comment]
@TImada I generated the *.dtb (according to the command in the image below) I put it in /boot (sdcard) I deleted the old bcm2711-rpi-4-b.dtb and I renamed its DTB to bcm2711-rpi-4-b.dtb. From then on, I don't get the U-boot screen either.

![Screenshot from 2023-01-02 17-42-22](https://user-images.githubusercontent.com/38701397/210276809-676f4ea2-443a-43b7-bb6b-a1e0ad6c88fc.png)

**Below is the sequence of commands I run when I get u-boot:**
```
setenv autostart yes
dcache off
fatload mmc 0:1 0x28000000 rpmsg_ping.elf
dcache flush
bootelf 0x28000000
(i can see everything Ok in ttyUSB1 in minicom)

fatload mmc 0:1 ${kernel_addr_r} kernel8.img
booti ${kernel_addr_r} - ${fdt_addr}

login/password in rpi4 1gb boot

(inside Linux Lite64bits_rpi4)
sudo ldconfig 
cd ~/raspi4/raspi4_freertos_rpmsg/samples/linux/rpmsg_echo/build
sudo ./rpmsg_echo
(At this moment I have the error of the image below:)
```
![209893767-3b011244-1199-4438-bb32-7527f303c470](https://user-images.githubusercontent.com/38701397/210277261-9f2aef1d-85a7-4130-915c-97a62a1feb5b.png)

**Comment by neuberfran** [comment]
@TImada I put device_tree=bcm2711-rpi-4-b-rtos.dtb in config.txt. But I didn't remove the bcm2711-rpi-4-b.dtb from the boot folder. I get an error as shown below:

```
ERROR: Did not find a cmdline Flattened Device Tree
Could not find a valid device tree
```

![Screenshot from 2023-01-02 20-16-12](https://user-images.githubusercontent.com/38701397/210284377-87f58dad-e9d1-414c-8a4c-31ac7a7d19fb.png)
![Screenshot from 2023-01-02 20-12-31](https://user-images.githubusercontent.com/38701397/210284382-cd0cb690-ed5a-4207-89b8-60ebf8ae7dfe.png)

**Comment by neuberfran** [comment]
@TImada 
![last](https://user-images.githubusercontent.com/38701397/210293010-a3a8ae2d-ead4-4651-b4d7-626146ced5c2.png)

**Do I need to reboot and put all the commands below every time I want in the echoes?**

> setenv autostart yes
> dcache off
> fatload mmc 0:1 0x28000000 rpmsg_ping.elf
> dcache flush
> bootelf 0x28000000
> 
> fatload mmc 0:1 ${kernel_addr_r} kernel8.img
> booti ${kernel_addr_r} - ${fdt_addr}
> 
> login/password in rpi4 1gb boot
> 
> sudo ldconfig 
> cd ~/raspi4/raspi4_freertos_rpmsg/samples/linux/rpmsg_echo/build
> sudo ./rpmsg_echo

![Screenshot from 2023-01-02 23-32-37](https://user-images.githubusercontent.com/38701397/210293383-92a53b97-3f1c-4782-8d83-d52ed0f41226.png)

**Comment by TImada** [comment]
> Do I need to reboot and put all the commands below every time I want in the echoes?

Yes, that is expected behavior. The FreeRTOS application releases the allocated resource then terminates once it sends a shutdown message to the Linux application.
(https://github.com/TImada/raspi4_freertos_rpmsg/blob/master/samples/freertos/rpmsg_ping/src/rpmsg-ping.c#L174)

You will have to learn rpmsg and remoteproc from documents found at [1] [2] if you want to change the behavior or to have your original application.
This repository does not cover i) the mechanism of rpmsg or remoteproc and ii) how to use them. (I will not answer questions on that)

[1] https://github.com/OpenAMP/open-amp/tree/main/doc
[2] https://github.com/OpenAMP/open-amp/wiki

**Comment by neuberfran** [comment]
@TImada 
I have a purpose for you. As I said at the beginning of this question, I have 3 imx7d-pico kits (old android things that now runs Yocto Hardknott). I didn't find the price I want to sell one and I'm a lover of RPMsg. I would send you one of those kits (SOC+carrier board) and you would help me implement OpenAMP/Remoteproc/RPMsg in that kit. Just like you did with the RPi4. That would be fine with me and give my imx7d-pico some finality.

**Comment by neuberfran** [comment]
@TImada 

Hello,

Friend, I would like to take advantage of this issue and count on your help to do the same as we did with the raspberry pi 4 on my device imx7d-pico by technexion. I have two of them here (I sold one at a lot of cost and I don't intend to sell another one for a low price, which would be the only way out)...

As I told you before, on this board (which runs yocto hardknott) I already did the RPMsg through u-boot bootloader/Linux/FreeRTOS.

Now I plan to use meta-openamp, but I'm not sure if this recipe only works for XIlinx(I just sent an email to the maintainer and he probably won't respond). As per the issue below, someone helped me upload meta-openamp on my device, but nothing appears in /sys/class/remoteproc folder:

https://github.com/OpenAMP/meta-openamp/issues/15

https://community.nxp.com/t5/i-MX-Processors/RPmsg-in-pico-imx7d-using-mainline-linux-5-6-xx-and-Yocto/m-p/1326535

But the ideal, serial to do the remoteproc

What do you think about all this?

https://lore.kernel.org/all/CAA07jV9w9_+S62Gv7WM2Kn-=6CNXy8mMEhOkGLKf3h2tGpFrSA@mail.gmail.com/
![photo01](https://user-images.githubusercontent.com/38701397/219982296-3ab8666c-d6c9-4316-a934-365d2d44009b.png)

**Comment by TImada** [comment]
You should use a Linux kernel officially provided by NXP. That's the easiest way to use OpenAMP/RPMSG.
Porting libmetal/open-amp to your device like what I did on Raspi4B requires further (and exact) knowledge on how RPMSG is implemented in Linux.

**Comment by neuberfran** [comment]
@TImada 

My device is imx7d-pico, but the link below shows that you are wrong about nxp RPMsg on linux upstream/mainline

https://community.nxp.com/t5/i-MX-Processors/Does-Freescale-iMX6-Linux-BSP-support-openAMP/m-p/455956

They had a kernel downstreem from them and used MCC and RPMsg_Lite/Virtio devices

In the video below, you can see that perhaps Zephyr is currently more prepared for RPMsg/remoteproc and/or openamp/libmetal. What do you think ?

https://www.youtube.com/watch?v=4XiDmpRY51Q

![photo07](https://user-images.githubusercontent.com/38701397/219990546-803eca75-56cf-4bec-bef3-70185214f3a5.png)

**Comment by TImada** [comment]
> My device is imx7d-pico, but the link below shows that you are wrong about nxp RPMsg on linux upstream/mainline
> https://community.nxp.com/t5/i-MX-Processors/Does-Freescale-iMX6-Linux-BSP-support-openAMP/m-p/455956
> They had a kernel downstreem from them and used MCC and RPMsg_Lite/Virtio devices

The URL above says nothing about RPMSG on iMX7D.
I know NXP provides RPMSG_lite rather than RPMSG. Both are implemented based on the virtio framework.
I cannot understand why you need to use RPMSG on iMX7D. RPMSG_lite would be enough for messaging between M4 and A7 cores.
If you want to use a newer Linux kernel, you can find a variety of Linux kernels for NXP processors at [1].

> In the video below, you can see that perhaps Zephyr is currently more prepared for RPMsg/remoteproc and/or openamp/libmetal. What do you think ?

I have never looked into the Zephyr implementation of RPMSG, so I cannot say nothing.

If you want to use RPMSG on iMX7D, that should be OK. My suggestion is the same as what other guys already told to you. You should make sure that you have loaded required kernel modules, then investigate what's happening at module loading.

[1] https://www.nxp.com/design/software/embedded-software/i-mx-software/embedded-linux-for-i-mx-applications-processors:IMXLINUX

**Comment by neuberfran** [comment]
@TImada 

First point, I decided now that I want to use Yocto/hardknott/TechNexion on the linux side in this project.
https://stackoverflow.com/questions/71831499/issue-virtio-rpmsg-bus-virtio0-msg-received-with-no-recipient-in-yocto-hardk
Note: The above link shows that I already got RPMsg using Yocto/uboot. And a path I know. Now I want something like what you got on the RPi4. But I still prefer remoteproc.

In fact, yesterday I discovered important/interesting things in the link below:

https://lore.kernel.org/all/CAA07jV9w9_+S62Gv7WM2Kn-=6CNXy8mMEhOkGLKf3h2tGpFrSA@mail.gmail.com/

The first is that Miss Wendy Liang takes care of meta-openamp for Xilinx and not meta-openamp in general:

https://github.com/OpenAMP/meta-openamp
https://github.com/Xilinx/meta-openamp

I would need someone to handle a meta-openamp for imx6/imx7/imx8

The second (important) part of the link is what Mr. Sanchayan says (about imx7 being better for **remoteproc** than A5 and M4 core on NXP Vybrid[1]:
```
>
> On iMX7 it might be achievable as the A7 and M4 core share certain 32 bit
> registers. On Vybrid, there are no such registers shared between the
> cores.
>
> Regards,
> Sanchayan.
```
![Screenshot from 2023-02-20 08-51-41](https://user-images.githubusercontent.com/38701397/220099706-2d9301ee-74e4-418a-bb1a-40d06bb85a8f.png)

**Comment by TImada** [comment]
> Note: The above link shows that I already got RPMsg using Yocto/uboot. And a path I know. Now I want something like what you got on the RPi4. But I still prefer remoteproc.

I have never tried remoteproc (which Linux kernel provides) with a uio-based RPMSG I have implemented for Raspi4B, so I cannot imagine what happens if you employ that combination on iMX7D. RPMSG coupled with remoteproc provided by Linux kernel may conflict with the uio-based RPMSG. (You will not see good helps or suggestions from me)

In addition, you can implement remoteproc functionality for processor lifecycle management in your Linux side application [1][2]. `remoteproc_{start,stop,shutdown}` invoke a registered handler (referred as `.start/.stop/.shutdown`) for a target processor.


> I would need someone to handle a meta-openamp for imx6/imx7/imx8

Why don't you do that by yourself?

[1] https://github.com/OpenAMP/open-amp/blob/main/apps/examples/load_fw
[2] https://github.com/OpenAMP/open-amp/blob/main/apps/examples/load_fw/zynqmp_apu_lcm_rproc_example.c#L173

**Comment by neuberfran** [comment]
@TImada 

You said "_Why don't you do that by yourself?_"

_I still don't have enough knowledge for that my friend.

It would be really nice if you did that.

**Comment by TImada** [comment]
> I still don't have enough knowledge for that

I did not have enough knowledge on FreeRTOS and Raspi4B at the start point of this porting too.

> It would be really nice if you did that.

Unfortunately, I cannot spare time to help your work as I have many other things to do.

**Comment by neuberfran** [comment]
@TImada What u do
???
?

**Comment by TImada** [comment]
My business work. Do not disturb me any more. :-)

**Comment by neuberfran** [comment]
@TImada Sorry

**Comment by neuberfran** [comment]
@TImada 

Unfortunately, I need you to help me with this issue below (that repository people never answer anything).

Any help is welcome

https://github.com/OpenAMP/meta-openamp/issues/34

**Comment by neuberfran** [comment]
@TImada Pls help-me more with RPMsg in imx7d-pico. I solved this issue with 2021.04 (Uboot Technexion/nxp uboot customized by me. And currently, on the same device, I have the same issue with U-boot 2022.04: https://stackoverflow.com/questions/71073386/reading-file-would-overwrite-reserved-memory-failed-to-load-hello-world-bin

**Comment by neuberfran** [comment]
@TImada 

Please delete this issue. There are many inconsistencies in the project and mainly due to the poor treatment I received at the end of this same issue.

**Comment by neuberfran** [comment]
@TImada

Please delete this issue. There are many inconsistencies in the project and mainly due to the poor treatment I received at the end of this same issue.

**Comment by neuberfran** [comment]
@TImada

Please delete this issue. There are many inconsistencies in the project and mainly due to the poor treatment I received at the end of this same issue.

**Comment by TImada** [comment]
Closed due to inactive status.

**Comment by neuberfran** [comment]
@TImada 

Yesterday I went to redo the project to learn OpenAMP with FreeRTOS and got two errors (as shown in the photos below):
1) The first when creating the app on the U-boot side (syslog.h is missing) I didn't find this file in the toolchain. Previously, this error did not occur.

2) The second was that the make command instead of cmake is not working:
![Screenshot from 2024-01-18 16-56-47](https://github.com/TImada/raspi4_freertos_rpmsg/assets/38701397/6d8d071d-8106-4a95-983c-672fb668b757)
![photo_121](https://github.com/TImada/raspi4_freertos_rpmsg/assets/38701397/bc2d514c-0716-4488-954e-ad4508fb9293)

**Comment by TImada** [comment]
Using `cmake`, not `make`, should solve the two problems.

Try the following:
```
$ cd ${RASPI4_BASE}/libmetal
$ mkdir build && cd build
$ cmake ../ -DCMAKE_TOOLCHAIN_FILE=../cmake/platforms/raspi4-freertos.cmake -DCMAKE_C_FLAGS="-I${RASPI4_BASE}/raspi4_freertos/FreeRTOS/Source/include -I${RASPI4_BASE}/raspi4_freertos/FreeRTOS/Source/portable/GCC/ARM_CA72_64_BIT -I${RASPI4_BASE}/raspi4_freertos_rpmsg/samples/freertos/rpmsg_ping/src -O2 -g3"
$ make VERBOSE=1
```

**Comment by neuberfran** [comment]
@TImada 
I command sudo ldconfig
before I command echo $LD_LIBRARY_PATH 
:/usr/local/lib
And
command Works Ok. But **make VERBOSE=1** have issue missing FreeRTOS.h lib

![Screenshot from 2024-01-19 20-57-48](https://github.com/TImada/raspi4_freertos_rpmsg/assets/38701397/217b8d49-1e87-402f-8405-1814e9917d9c)
![Screenshot from 2024-01-19 20-58-04](https://github.com/TImada/raspi4_freertos_rpmsg/assets/38701397/09798898-f03a-432b-900e-09a32a823bf7)

**Comment by TImada** [comment]
`${RASPI4_BASE}` is missing (empty) in your environment. `cmake` generates a wrong path to search header files in that case.

See https://github.com/TImada/raspi4_freertos_rpmsg/blob/master/docs/freertos_build.md#1-create-a-dedicated-directory to set it.

**Comment by neuberfran** [comment]
@TImada 
Sorry
But now I have issue in open-amp build:
  Could not find toolchain file: ../cmake/platforms/raspi4_a72_generic.cmake
![Screenshot from 2024-01-20 14-42-47](https://github.com/TImada/raspi4_freertos_rpmsg/assets/38701397/12ce250f-f335-4657-81ba-37eb90a5595a)

**Comment by TImada** [comment]
I have updated libmetal/open-amp submodules.

Try the entire build process again from https://github.com/TImada/raspi4_freertos_rpmsg/blob/master/docs/freertos_build.md#3-clone-freertos-rpmsg-sample

**Comment by neuberfran** [comment]
@TImada 
[1] https://www.youtube.com/watch?v=mFgiIXv7b5U
[2] https://groups.google.com/g/open-amp/c/muD2nZayhAM
[3] https://embeddeduse.com/2017/06/03/cmake-cross-compilation-based-on-yocto-sdk/
[4] https://www.reddit.com/r/embeddedlinux/comments/o0eou2/comment/h24pfgd/?rdt=46336

Everything works ok. But....
I have the project of packaging your project in Yocto (before migrating your entire project to my imx7d-pico by technexion, we already talked about deploying OpenAMP/RPMsg/Remoteproc in this device=imx7d-pico)

I already have Yocto Kirskstone [4] running on my rpi4 (& ONLY Yocto in imx7d-pico)  and I can run rpmsg_echo but I have already placed the executable (rpmsg_echo) directly there. I want to build it together[1] with Yocto and use meta-openamp[2] from this repository:
https://github.com/OpenAMP/meta-openamp

In Video [1]  At minute 7 and 31 seconds, the author mentions some things I would like to ask him before using:

1) What version of FreeRTOS did you use in your project with rpi4?
1.1) Can I use FreeRTOS 10.2.1 (8",10s in video)  as the video author used in this Yocto/OpenAMP/RPMsg project on rpi4?
1.2) Can I use TCLIB = "newlib"?

2) What do you think about the libmetal and openamp libs generated (according to ls command) via direct build of meta-openamp [2] on Yocto? Could the different numbering cause an error in FreeRTOS/Linux in the end?
```
root@raspberrypi4-64:/usr/lib# ls libme*.*
libmetal.so.0      libmetal.so.1      libmetal.so.1.5.0
root@raspberrypi4-64:/usr/lib# ls libopen*.*
libopen_amp.so.0      libopen_amp.so.1      libopen_amp.so.1.5.0
root@raspberrypi4-64:/usr/lib# pwd
/usr/lib
root@raspberrypi4-64:/usr/lib# uname -a
Linux raspberrypi4-64 5.15.92-v8 #1 SMP PREEMPT Wed Feb 8 16:47:50 UTC 2023 aarch64 GNU/Linux
```

3) Do you think that by implementing meta-freertos [1] and meta-openamp[2] I will be able to package your project in Yocto ? (Look: Observation-01 - local.conf (Yocto Kirsktone build))

**Observation-01 - local.conf (Yocto Kirsktone build)**

```
MACHINE ?= "raspberrypi4-64"

DISTRO ?= "poky"
PACKAGE_CLASSES ?= "package_rpm"
EXTRA_IMAGE_FEATURES = "debug-tweaks ssh-server-dropbear package-management"
IMAGE_INSTALL:append = "libmetal open-amp kernel-modules "

USER_CLASSES ?= "buildstats"
PATCHRESOLVE = "noop"
BB_DISKMON_DIRS ??= "\
    STOPTASKS,${TMPDIR},1G,100K \
    STOPTASKS,${DL_DIR},1G,100K \
    STOPTASKS,${SSTATE_DIR},1G,100K \
    STOPTASKS,/tmp,100M,100K \
    HALT,${TMPDIR},100M,1K \
    HALT,${DL_DIR},100M,1K \
    HALT,${SSTATE_DIR},100M,1K \
    HALT,/tmp,10M,1K"
PACKAGECONFIG:append:pn-qemu-system-native = " sdl"
CONF_VERSION = "2"
ENABLE_UART = "1"
RPI_USE_U_BOOT = "1"
```

**Comment by TImada** [comment]
> 1. What version of FreeRTOS did you use in your project with rpi4?
>    1.1) Can I use FreeRTOS 10.2.1 (8",10s in video)  as the video author used in this Yocto/OpenAMP/RPMsg project on rpi4?
>    1.2) Can I use TCLIB = "newlib"?

v10.3.0 is used. I don't know what is different between v10.3.0 and v10.2.1, but v10.2.1 would work if it has compatible APIs with APIs provided by v10.3.0.
newlib would work if you use it instead of musl_libc found at https://github.com/TImada/raspi4_freertos/tree/master/FreeRTOS/Demo/CORTEX_A72_64-bit_Raspberrypi4/musl_libc.

> 2. What do you think about the libmetal and openamp libs generated (according to ls command) via direct build of meta-openamp [2] on Yocto? Could the different numbering cause an error in FreeRTOS/Linux in the end?

libmetal/open-amp version (git tag name) used for this repository is v2020.04.0.
I'm not sure what happens if you use another version of libmetal/open-amp.

> 3. Do you think that by implementing meta-freertos [1] and meta-openamp[2] I will be able to package your project in Yocto ? (Look: Observation-01 - local.conf (Yocto Kirsktone build))

I cannot have any good answer on this as I'm not a yocto guy.

**Comment by neuberfran** [comment]
@TImada 

We already talked about /dev/ttyRPMSG (via remoteproc app) on my imx7d-pico.
https://github.com/zephyrproject-rtos/zephyr/issues/69433

I've had this issue above for almost a month and you can help me in two ways:

1) Interacting on the issue and responding as much as possible

2) Adapting your rpi4/FreeRTOS/Remoteproc/Messages project to use /dev/ttyRPMSG (rpmsg_tty kernel driver)

**Comment by TImada** [comment]
I do not have any motivation to conduct both 1. and 2. as that's your business, not mine.

**Comment by neuberfran** [comment]
@TImada Hi,I'm trying this again today (with the latest versions of U-boot and kernel), in fact, I just resolved a device-tree port error in bcm2711-rpi-4-b.dtb: https://stackoverflow.com/questions/78744626/issue-in-rpi4-8gb-when-i-try-change-bcm2711-rpi-4-b-dtb-in-debian-12-64-bits

The problem now is(Resetting CPU ... resetting ...) that Uboot restarts itself (as shown in the photo below and like type this:https://github.com/raspberrypi/firmware/issues/1157), making it impossible for me to go to cd ./raspi4/raspi4_freertos_rpmsg/samples/linux/rpmsg_echo/build (where everything is already ready) and command:
sudo ldconfig
sudo ./rpmsg_echo

```
U-Boot 2024.04-rc4-00040-gbd0aedde3e-dirty (Mar 23 2024 - 10:37:01 -0300)

DRAM:  948 MiB (effective 7.9 GiB)
RPI 4 Model B (0xd03115)
Core:  211 devices, 15 uclasses, devicetree: board
MMC:   mmcnr@7e300000: 1, mmc@7e340000: 0
Loading Environment from FAT... Unable to read "uboot.env" from mmc0:1... 
In:    serial,usbkbd
Out:   serial,vidconsole
Err:   serial,vidconsole
Net:   eth0: ethernet@7d580000
starting USB...
No working controllers found
Hit any key to stop autoboot:  0 
Card did not respond to voltage select! : -110
** Booting bootflow 'mmc@7e340000.bootdev.part_1' with script
3371128 bytes read in 181 ms (17.8 MiB/s)
25661952 bytes read in 1158 ms (21.1 MiB/s)
Moving Image from 0x80000 to 0x200000, end=1b90000
## Flattened Device Tree blob at 2eff1e00
   Booting using the fdt blob at 0x2eff1e00
Working FDT set to 2eff1e00
   Using Device Tree in place at 000000002eff1e00, end 000000002f002f3d
Working FDT set to 2eff1e00
"Synchronous Abort" handler, esr 0x96000061, far 0x3af3901c
elr: 0000000000089eac lr : 0000000000089e50 (reloc)
elr: 000000003b355eac lr : 000000003b355e50
x0 : 0000000000000001 x1 : 0000000000000001
x2 : 0000004000000000 x3 : 0000000000000008
x4 : 000000000000000c x5 : 0000000000000008
x6 : 00000000000000b8 x7 : 0000000000000003
x8 : 000000002eff1e00 x9 : 00000000000000a8
x10: 000000003af38e8c x11: 0000000000009e9c
x12: 000000003af38f88 x13: 000000002eff1e00
x14: 00000000ffffffff x15: 000000003af39048
x16: 000000003b35904c x17: 0000000000000000
x18: 000000003af47d60 x19: 000000003af3901c
x20: 0000000000000004 x21: 0000000000000002
x22: 000000003af39060 x23: 000000003af39080
x24: 000000002eff1e00 x25: 000000003b3c8055
x26: 0000000000000000 x27: 0000000000000000
x28: 000000003af55830 x29: 000000003af38f80

Code: 5ac00842 540001c1 f8617ac2 dac00c42 (f9000262) 
Resetting CPU ...

resetting ...

```
My **boot.scr** (old cmdline.txt file that I haven't used here) is:
```
setenv autostart yes
dcache off
fatload mmc 0:1 0x28000000 rpmsg_ping.elf
dcache flush
bootelf 0x28000000
fatload mmc 0:1 ${kernel_addr_r} Image
setenv bootargs "8250.nr_uarts=1 console=ttyS0,115200 root=/dev/mmcblk0p2 rootwait rw maxcpus=3"
booti ${kernel_addr_r} - ${fdt_addr}
```
![Screenshot from 2024-07-23 19-01-02](https://github.com/user-attachments/assets/89d41d9e-b3e2-4551-b783-aa6985700316)

**Comment by TImada** [comment]
Your boot.scr seems wrong.

Follow https://github.com/TImada/raspi4_freertos#launching-freertos and replace uart.elf by rpmsg_ping.elf.

**Comment by neuberfran** [comment]
@TImada 

I can't see anything wrong with my boot.scr. I'm making changes to U-boot 2024.04
1)
#CONFIG_USB_XHCI_HCD=y
#CONFIG_USB_XHCI_PCI=y

2) I try with uboot 2021.04 and 2021.10 
But not solved yet


boot.scr
```
setenv autostart yes
dcache off
fatload mmc 0:1 0x28000000 rpmsg_ping.elf
dcache flush
bootelf 0x28000000
fatload mmc 0:1 ${kernel_addr_r} Image
setenv bootargs "8250.nr_uarts=1 console=ttyS0,115200 root=/dev/mmcblk0p2 rootw>
booti ${kernel_addr_r} - ${fdt_addr}
```

**Comment by neuberfran** [comment]
@TImada How to create rpmsg_ping.bin (not *.ELF) ? https://stackoverflow.com/questions/75475302/synchronous-abort-handler-esr-0x96000004

**Comment by TImada** [comment]
You should have a diff between your boot.scr and what I have introduced in https://github.com/TImada/raspi4_freertos_rpmsg/issues/1#issuecomment-2247941043. You will see i) a different ELF load address and ii) missing `dcache on`.

Considering .bin does not make sense now as your faulty boot.scr can easily cause data inconsistency on RAM.

**Comment by neuberfran** [comment]
@TImada 
Pls What about failed to open the GIC device: -2? -2?
You can see that I have all the files in the device-tree
```
sudo ./rpmsg_echo 
Starting application...
ERROR: failed to open the GIC device: -2.
ERROR: Failed to create remoteproc device.
ERROR: Failed to initialize platform.
Stopping application...
Segmentation fault
neuberfran@raspberrypi:~/raspi4/raspi4_freertos_rpmsg/samples/linux/rpmsg_echo/build$ ls /proc/device-tree/arm
armlocal_uio@ff800000/ arm-pmu/               
neuberfran@raspberrypi:~/raspi4/raspi4_freertos_rpmsg/samples/linux/rpmsg_echo/build$ ls /proc/device-tree/armlocal_uio@ff800000/
compatible  interrupt-parent  interrupts  name	reg  status
neuberfran@raspberrypi:~/raspi4/raspi4_freertos_rpmsg/samples/linux/rpmsg_echo/build$ ls /proc/device-tree/shm@20600000/
compatible  name  reg  status
neuberfran@raspberrypi:~/raspi4/raspi4_freertos_rpmsg/samples/linux/rpmsg_echo/build$ ls /proc/device-tree/gic_uio@40041000/
compatible  name  reg  status
neuberfran@raspberrypi:~/raspi4/raspi4_freertos_rpmsg/samples/linux/rpmsg_echo/build$ ls /proc/device-tree/reserved-memory/rtos@20000000/
alloc-ranges  compatible  name	no-map	size
neuberfran@raspberrypi:~/raspi4/raspi4_freertos_rpmsg/samples/linux/rpmsg_echo/build$ 
```
https://gist.github.com/neuberfran/421e1a1ec38f45226a4a3d37f1fc32ec
![Screenshot from 2024-07-25 14-24-15](https://github.com/user-attachments/assets/1be748f6-5f51-4f42-ae40-e240ab356ba1)

**Comment by TImada** [comment]
Why don't you debug it by gdb to clarify what is wrong? I cannot imagine what have you done exactly due to less information on your raspi4.
`-2` is returned at [1]. So  you can start debugging with [2].

(I won't be able to reply at all until mid of August as I'll be off from several hours later.)

[1] https://github.com/TImada/open-amp/blob/fa1856e5a670298123a521d141b42ce5573d4a85/apps/machine/raspi4/raspi4_a72_rproc.c#L112
[2] https://github.com/TImada/libmetal/blob/7828b6f749aa0b7548c3033c78b97b4b6956c9af/lib/device.c#L54

**Comment by neuberfran** [comment]
@TImada I know you are very busy. I still have the same error above.
I bought an FT232H from aliexpress that only arrives in the second half of August/24. A great clue has appeared to solve my issue.

1)
I have one system with kernel 5.15. Works

```
./rpmsg_echo
Starting application...
metal: info:      metal_uio_dev_open: No IRQ for device 40041000.gic_uio.
metal: info:      metal_uio_dev_open: No IRQ for device 20600000.shm.
uname -a
Linux raspberrypi4-64 5.15.92-v8 #1 SMP PREEMPT Wed Feb 8 16:47:50 UTC 2023 aarch64 GNU/Linux
```

I have other system with kernel 6.6. Not Works and it:

```
metal: info:      metal_uio_dev_open: No IRQ for device 40041000.gic_uio.
metal: info:      metal_uio_dev_open: No IRQ for device 20600000.shm.
```
Not appear

2) 

```
sudo ldconfig
neubercd ${RASPI4_BASE}/raspi4_freertos_rpmsg/samples/linux/rpmsg_echo/build^C
neuberfran@raspberrypi:~/raspi4/raspi4_freertos_rpmsg/samples/linux/rpmsg_echo/build$ sudo ./rpmsg_echo
Starting application...
Passei aki 1Passei aki 2Passei aki 10: platform
Passei aki 4ERROR: failed to open the GIC device: -2.
ERROR: Failed to create remoteproc device.
ERROR: Failed to initialize platform.
Stopping application...
Segmentation fault
```
On the working system I have /dev/ttyAMA0. On the non-working one, this does not appear. I am sure that changes were made to the Linux kernel (in this part of ttyAMA0, ttyAMA1) but I am not sure if this is the cause of my current issue (
https://github.com/raspberrypi/linux/issues/5566

3)

I have absences (in the kernel 6.6 image with error) of interrupts shown by the command: cat /proc/interrupts

```
cat /proc/interrupts
           CPU0       CPU1       CPU2       
  9:          0          0          0     GICv2  25 Level     vgic
 11:      47920      47312      46982     GICv2  30 Level     arch_timer
 12:          0          0          0     GICv2  27 Level     kvm guest vtimer
 14:       1501          0          0     GICv2  65 Level     fe00b880.mailbox
 15:          0          0          0     GICv2 114 Level     DMA IRQ
 26:          0          0          0     GICv2 175 Level     PCIe PME, aerdrv
 27:       1953          0          0     GICv2 189 Level     eth0
 28:        125          0          0     GICv2 190 Level     eth0
 29:         38          0          0  BRCM STB PCIe MSI 524288 Edge      xhci_hcd
 30:          1          0          0     GICv2  66 Level     VCHIQ doorbell
 31:          0          0          0     GICv2  48 Level     arm-pmu
 32:          0          0          0     GICv2  49 Level     arm-pmu
 33:          0          0          0     GICv2  50 Level     arm-pmu
 34:          0          0          0     GICv2  51 Level     arm-pmu
 36:       2870          0          0     GICv2 125 Level     ttyS0
 37:      39605          0          0     GICv2 158 Level     mmc1, mmc0
IPI0:      7362       7173       7207       Rescheduling interrupts
IPI1:     34873      46177      39800       Function call interrupts
IPI2:         0          0          0       CPU stop interrupts
IPI3:         0          0          0       CPU stop (for crash dump) interrupts
IPI4:         0          0          0       Timer broadcast interrupts
IPI5:       925        989        727       IRQ work interrupts
IPI6:         0          0          0       CPU wake-up interrupts
```
![Screenshot from 2024-08-01 22-15-25](https://github.com/user-attachments/assets/55dad860-ca36-4bfc-80d7-d0fa79ac6b31)

**Comment by neuberfran** [comment]
https://forums.raspberrypi.com/viewtopic.php?t=374582

**Comment by neuberfran** [comment]
@TImada https://gist.github.com/tnishinaga/46a3380e1f47f5e892bbb74e55b3cf3e

Even commenting the necessary lines, this command above presents an error below

```
Open On-Chip Debugger 0.12.0+dev-00682-gefe902219 (2024-08-09-23:01)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
DEPRECATED! use 'adapter speed' not 'adapter_khz'
Warn : Transport "jtag" was already selected
Warn : DEPRECATED! use '-baseaddr' not '-ctibase'
Warn : DEPRECATED! use '-baseaddr' not '-ctibase'
Warn : DEPRECATED! use '-baseaddr' not '-ctibase'
Warn : DEPRECATED! use '-baseaddr' not '-ctibase'
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : clock speed 1000 kHz
Error: JTAG scan chain interrogation failed: all ones
Error: Check JTAG interface, timings, target power, etc.
Error: Trying to use configured scan chain anyway...
Error: auto0.tap: IR capture error; saw 0x0f not 0x01
Warn : Bypassing JTAG setup events due to errors
Error: Invalid ACK (7) in DAP response
Error: JTAG-DP STICKY ERROR
```
The only one who accepts is this one:
https://gist.github.com/neuberfran/5186f86a623187e49faf71f9ce8233d5
Maybe because my ft232h is from Aliexpress and not from Adafruit. I am not sure
https://pt.aliexpress.com/item/32814913865.html?spm=a2g0o.productlist.main.1.4a40bCqEbCqEAh&algo_pvid=d1fef58c-7997-4c14-b1e7-6c581470c1e3&algo_exp_id=d1fef58c-7997-4c14-b1e7-6c581470c1e3-0&pdp_npi=4%40dis%21BRL%2136.83%2136.83%21%21%216.39%216.39%21%402101fb0b17235868191183229ec2b2%2164641947041%21sea%21BR%21168391086%21X&curPageLogUid=v7HdIp3UtDGs&utparam-url=scene%3Asearch%7Cquery_from%3A

**Comment by neuberfran** [comment]
https://www.youtube.com/watch?v=hKNhQPoA8kY

**Comment by TImada** [comment]
Report your debugging result on Linux including;

(1) values of `prproc->bus_name`, `prproc->gic_name`, `prproc->armlocal_name` and `prproc->shm_name` in `raspi4_a72_proc_init()`
(2) command outputs
```sh
$ hexdump -C /proc/device-tree/armlocal_uio@ff800000/*
$ hexdump -C /proc/device-tree/gic_uio@40041000/*
$ hexdump -C /proc/device-tree/shm@20600000/*
$ hexdump -C /proc/device-tree/reserved-memory/rtos@20000000/*
$ ls /sys/bus/platform/devices/40041000.gic_uio/
$ ls /sys/bus/platform/devices/20600000.shm/
$ ls /sys/bus/platform/devices/ff800000.armlocal_uio/
```

**Comment by neuberfran** [comment]
@TImada How to Start rpmsg_echo from gdb/JTAG/openocd

**Comment by TImada** [comment]
`sudo -E gdb /path/to/rpmsg_echo` on your Rasp4 Linux would be enough.

**Comment by neuberfran** [comment]
@TImada Actually, sudo -E gdb /path/to/rpmsg_echo on your Rasp4 Linux would be enough worked, but...

As shown in the photo below, the ft232h is attached to the computer (USB) and not to the rpi4 USB.
![20240830_143041](https://github.com/user-attachments/assets/6a90e7d5-49c3-4e47-8a79-482c0a2bb40c)

Therefore, I can only give the command below on the computer and not on the rpi4:
./src/openocd -f  ~/openocd-code/tcl/interface/rpi4.cfg -f ~/openocd-code/tcl/target/bcm2711.cfg

Therefore, the commands: target extended-remote localhost:3333 and/Or target ext :3333   (from within the rpi4 gdb) do not work( Connection timed out.). Probably because openocd is running on the computer:
![Screenshot from 2024-08-30 14-39-25](https://github.com/user-attachments/assets/3908233e-8a59-421f-a707-3554bae5e69b)

When I manage to run both commands from within the computer I get kernel panic and the error: "0x03047d53"
This is not a random error as this person has already reported the problem and has not resolved it.
https://sourceforge.net/p/openocd/mailman/openocd-user/thread/c9759b95c44f43868b342bee4024245d@b-plus.com/

**Comment by neuberfran** [comment]
> Report your debugging result on Linux including;
> 
> (1) values of `prproc->bus_name`, `prproc->gic_name`, `prproc->armlocal_name` and `prproc->shm_name` in `raspi4_a72_proc_init()` (2) command outputs
> 
> ```shell
> $ hexdump -C /proc/device-tree/armlocal_uio@ff800000/*
> $ hexdump -C /proc/device-tree/gic_uio@40041000/*
> $ hexdump -C /proc/device-tree/shm@20600000/*
> $ hexdump -C /proc/device-tree/reserved-memory/rtos@20000000/*
> $ ls /sys/bus/platform/devices/40041000.gic_uio/
> $ ls /sys/bus/platform/devices/20600000.shm/
> $ ls /sys/bus/platform/devices/ff800000.armlocal_uio/
> ```
https://www.youtube.com/watch?v=Fw8GwKnr_8I

**Comment by TImada** [comment]
You don't need to use OpenOCD and a JTAG probe to debug `rpmsg_echo`.
Use SSH to log-in your Raspi4 then invoke `sudo -E gdb ...`.
